Feat(Dir/Difference): See Difference Between Dir Files & Content
assert-rs/dir-diff pull request #20
Opened 2018-08-07 01:09 UTC by TNkemdilim

Print out the difference between any two directories to stdout. This includes:
- Difference between lines in files
- Existence of a file or not

**A sample output is:**
```
╔════════════════════════════════════════════════════════════════════════╗
║                               Differences                              ║
╠════════════════════════╦═══════════════════════╦═══════════════════════╣
║ Filename               ║ tests/easy/bad/dir1   ║ tests/easy/bad/dir2   ║
╠════════════════════════╬═══════════════════════╬═══════════════════════╣
║ /sample.txt            ║ FILE EXISTS           ║ DOESN'T EXIST         ║
╠════════════════════════╬═══════════════════════╬═══════════════════════╣
║ "/test.txt":1          ║ testing testing       ║ oh no!                ║
╠════════════════════════╬═══════════════════════╬═══════════════════════╣
║ "/test.txt":2          ║ skdjjd                ║                       ║
╚════════════════════════╩═══════════════════════╩═══════════════════════╝
```

- [ ] Tests created for any new feature or regression tests for bugfixes.
- [ ] `cargo test` succeeds
- [ ] `cargo +nightly clippy` succeeds

2018-08-07 03:07 UTC, epage requested changes
Hey, thanks for contributing!

A question I have though is if a view (e.g. table) belongs in dir-diff or only a model (e.g. iterator of results).

This is related to issue #11 which I experimented with in #17.  I'm mixed on the results there and haven't had time to further experiment on it.

Additionally, I've been curious about integrating dir diffing into `predicates` so it can work with a testing library like `assert_fs`.  See https://github.com/assert-rs/predicates-rs/issues/33

2018-08-07 03:07 UTC, epage commented on src/lib.rs
> +                    match (&buffreader_a.next(), &buffreader_b.next()) {
Would using [`zip_longest`](https://docs.rs/itertools/0.6.0/itertools/trait.Itertools.html#method.zip_longest) with an [enumerate](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.enumerate) work here?

2018-08-07 03:07 UTC, epage commented on Cargo.toml
> +term-table = "0.1.5"
If we move forward with this, should printing the table be a feature that opts into `term-table` as an optional dependency?

For people who don't want all of the extra stuff, this might be heavy weight to force onto them.

2018-08-07 03:10 UTC, epage requested changes

2018-08-07 03:10 UTC, epage commented on src/lib.rs
> +    println!("{}", table.as_string());
Additional question I had for this.  Should it unconditionally print the results or should it return a renderable struct that people can ask if the dirs are different.  This would open it up so users could optionally print if there is a difference.

2018-08-07 03:10 UTC, epage commented on src/lib.rs
> +                            match (line_a, line_b) {
Depending on how we solve binary files, should this instead use the `difference` crate rather than re-implementing file diffing ourselves?

2018-08-07 03:10 UTC, epage commented
Also, could you share what your use case is?  It'd be helpful to better understand the larger picture of what you are trying to accomplish.

2018-08-18 21:04 UTC, epage requested changes
Thanks for responding to my first round of feedback.  In this round, I cover some more design questions and trade offs.  You are welcome to go ahead and work on them and we can continue to iterate on each round until we come to a design that works.

I will note that I've known people who tend to get burnt out with that though and I don't want that to happen with you.  Something that can help is first discussing the requirements in #11 and https://github.com/assert-rs/predicates-rs/issues/33 and proposing a solution in #11.  We can then iterate in the comments of #11 on the concepts before taking the time to write the code.

2018-12-08 08:14 UTC, TNkemdilim commented
Sorry, I haven't had time to work on this, as I've been busy for the past months. I'll try to address this ASAP. 

Sorry for the delay.

2018-12-08 17:34 UTC, epage commented
Understandable; we all have those times.

2026-04-21 00:44 UTC, closed without merging